### ISSUE TITLE
Naming?

### ISSUE THREAD

**Issue by ljharb** [leobalter/object-keysin-valuesin-entries-in#2]
Personally I'm not a fan of the "fooIn" names - I suspect many will have bikeshedding opinions.

I think it would behoove us to gather everyone's naming thoughts in one place - perhaps this thread - so that any decision can be made with as much confidence as possible.

**Comment by leobalter** [comment]
getting into the bikeshed: `enumerable{Keys,Values,Entries}` sounds good too.

I don't have any preference that I'm really attached to, but this suggestion works really well with an extra `allKeys, ...` if we want extra methods to enumerate symbol keys as well.

**Comment by ljharb** [comment]
`enumerableFoo` seems nice to me as well

**Comment by jdalton** [comment]
@ljharb
I'm not super attached to the `In` postfix (I use it in lodash because small names and convention win) but ECMAScript has a history of very long descriptive names (it also avoids potential collisions) so that's cool. On the bikeshedding `enumerableFoo` doesn't imply inherited though.

@leobalter 
I'm glad you brought up `allKeys` as including symbols (I recently added internal helpers [for](https://github.com/lodash/lodash/blob/4.7.0-npm/_getAllKeys.js) - [that](https://github.com/lodash/lodash/blob/4.7.0-npm/_getAllKeysIn.js)).

**Comment by jdalton** [comment]
`enumerableFoo` doesn't imply inherited though.

**Comment by ljharb** [comment]
My first response is "Inherited is always implied in JS, unless "own" is in the name - with the legacy exception of `Object.keys` (and thus values/entries)" but then there's Object.assign as well.

So, I'm not convinced there's an automatic implication, and to me, "enumerableFoo" doesn't imply "own".

**Comment by jdalton** [comment]
> My first response is "Inherited is always implied in JS, unless "own" is in the name

It is until it's not. `Object.keys` unlike other (`Object.getOwnPropertyNames` which is just as old) methods doesn't have an `own` or `enumerable` in its name. The exceptions (O.keys, O.values, O.entries, etc.) start to add up and form their own convention which strengthens the `In` postfix case.

Maybe instead of having `own` and `inherited` forms of all these methods there's another way?

**Comment by jdalton** [comment]
The exceptions (O.keys, O.values, O.entries, etc) start to add up and form their own convention.

**Comment by jdalton** [comment]
Maybe instead of having `own` and `inherited` forms of all these methods there's another way?

**Comment by ljharb** [comment]
The only way I can think of is either a "get prototype chain" method that could be `.map`ped with an "own" method (useful but probably hard to get through), or, a boolean flag (API code smell)

**Comment by leobalter** [comment]
> I'm glad you brought up allKeys as including symbols (I recently added internal helpers for - that).

That was brought up by @ljharb on a private conversation before this issue, I just registered it here.

---

bikesheding, I have to say `.mapKeys .mapVaues .mapEntries` seems interesting. Still, the `enumerable__` seems consistent with the language used internally on the specs.

**Comment by leobalter** [comment]
current potential candidates:
- `Object.enumerableFoos`
- `Object.mapFoos`
- `Object.foosIn`

I'm afraid the `.map*` names might bring a new terminology to the specs, where `enumerable*` works well with the current language.

Thinking one step ahead, `.mapAllFoos` works really nice combined with `.mapFoos`

**Comment by jdalton** [comment]
The name `map` makes me think of `Array#map` or `Map`.

**Comment by leobalter** [comment]
> The name `map` makes me think of `Array#map` or `Map`.

That's a great reason to keep the bikeshed on. I agree with you.

**Comment by leobalter** [comment]
any other suggestion we should try? I'm planning to add this proposal soon, potentially adding it to the agenda for the next meeting.

**Comment by ljharb** [comment]
I think https://github.com/leobalter/object-keysin-valuesin-entries-in/issues/2#issuecomment-203562853 is the best option so far.

**Comment by jdalton** [comment]
Of the non-`in` forms ya.

**Comment by azz** [comment]
Just wanted to throw `Object.proto{Keys,Values,Entries}` (or `Object.prototype{Keys,Values,Entries}`) out there as an alternative. The only reason I don't like `enumerable` is that `Object.{keys,values,entries}` already includes only enumerable properties. The difference between the set of functions is not enumerability, it is inheritance.
